#!/usr/bin/env bash
#
# Parse UFW logs into readable text, JSON Lines, or CSV.

set -euo pipefail

default_infile=/var/log/ufw.log
format=text
input=

# Build a compact interface-to-MAC map for outbound local traffic. UFW does
# not always include MAC= for packets generated by the host, so the parser
# fills that gap from the outbound interface when it can.
collect_interface_macs() {
    # Tests and scripted callers can provide a deterministic map in the form
    # "eth0=aa:bb:cc:dd:ee:ff;wlan0=11:22:33:44:55:66".
    if [[ -n "${UFW_LOG_PARSER_IFACE_MACS:-}" ]]; then
        printf '%s\n' "$UFW_LOG_PARSER_IFACE_MACS"
        return
    fi

    # Linux systems normally provide the most parseable link data via ip(8).
    if command -v ip >/dev/null 2>&1; then
        ip -o link show 2>/dev/null | awk '
            {
                iface = $2;
                sub(/:$/, "", iface);
                for (i = 1; i <= NF; i++) {
                    if ($i == "link/ether" && (i + 1) <= NF) {
                        print iface "=" $(i + 1);
                    }
                }
            }
        '
        return
    fi

    # macOS and BSD systems generally have ifconfig(8), with ether lines
    # nested under each interface block.
    if command -v ifconfig >/dev/null 2>&1; then
        ifconfig -a 2>/dev/null | awk '
            /^[A-Za-z0-9_.:-]+:/ {
                iface = $1;
                sub(/:$/, "", iface);
            }
            /^[[:space:]]*ether[[:space:]]/ && iface != "" {
                print iface "=" $2;
            }
        '
    fi
}

usage() {
    cat <<'EOF'
Usage:
  ufw_log_parser.sh [--text|--jsonl|--csv] [logfile|-]

Examples:
  ufw_log_parser.sh
  ufw_log_parser.sh /var/log/ufw.log
  tail -n 30 /var/log/ufw.log | ufw_log_parser.sh -
  tail -F /var/log/ufw.log | ufw_log_parser.sh --jsonl -

Options:
  --text       Human-readable output. This is the default.
  --jsonl      Emit one JSON object per parsed UFW event.
  --csv        Emit CSV with a header row.
  -h, --help   Show this help.
EOF
}

while (($#)); do
    case "$1" in
        --text)
            format=text
            ;;
        --jsonl|--json)
            format=jsonl
            ;;
        --csv)
            format=csv
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        -)
            if [[ -n "$input" ]]; then
                printf 'Only one input file may be provided.\n\n' >&2
                usage >&2
                exit 2
            fi
            input=$1
            ;;
        -*)
            printf 'Unknown option: %s\n\n' "$1" >&2
            usage >&2
            exit 2
            ;;
        *)
            if [[ -n "$input" ]]; then
                printf 'Only one input file may be provided.\n\n' >&2
                usage >&2
                exit 2
            fi
            input=$1
            ;;
    esac
    shift
done

# A bare "--" stops option parsing; accept a single path after it.
if (($#)); then
    if [[ -n "$input" || $# -gt 1 ]]; then
        printf 'Only one input file may be provided.\n\n' >&2
        usage >&2
        exit 2
    fi
    input=$1
fi

# No input argument means "parse the normal UFW log". A literal "-" means
# read from stdin, which lets callers pre-filter large logs with tail/grep.
if [[ -z "$input" ]]; then
    input=$default_infile
fi

if [[ "$input" != "-" && ! -r "$input" ]]; then
    printf 'Cannot read UFW log: %s\n' "$input" >&2
    exit 1
fi

iface_macs=$(collect_interface_macs)
# BSD awk rejects literal newlines in -v values, so pass the map as one
# semicolon-delimited string.
iface_macs=${iface_macs//$'\n'/;}

awk -v format="$format" -v iface_macs="$iface_macs" '
BEGIN {
    OFS = ",";

    # Rehydrate the shell-provided interface MAC map into an awk array.
    split(iface_macs, mac_lines, ";");
    for (i in mac_lines) {
        if (mac_lines[i] == "") {
            continue;
        }
        split(mac_lines[i], mac_pair, "=");
        if (mac_pair[1] != "" && mac_pair[2] != "") {
            local_macs[mac_pair[1]] = mac_pair[2];
        }
    }
    if (format == "csv") {
        print "timestamp,action,interface_in,interface_out,src_mac,src_ip,dst_ip,src_port,dst_port,protocol,event,length,ttl,raw";
    }
}

/\[UFW / {
    reset_event();
    raw = $0;
    ts = substr($0, 1, 15);

    # UFW can emit other bracketed messages; keep only events with a known
    # firewall action.
    if ($0 ~ /\[UFW BLOCK\]/) {
        action = "BLOCK";
    } else if ($0 ~ /\[UFW ALLOW\]/) {
        action = "ALLOW";
    } else if ($0 ~ /\[UFW AUDIT\]/) {
        action = "AUDIT";
    } else {
        next;
    }

    # UFW log fields are emitted as KEY=value tokens. Parse them once per
    # event and reuse the array instead of scanning the raw line repeatedly.
    for (i = 1; i <= NF; i++) {
        if ($i ~ /^[A-Z0-9_]+=/) {
            key = $i;
            sub(/=.*/, "", key);
            value = $i;
            sub(/^[^=]*=/, "", value);
            fields[key] = value;
        }
    }

    src = get_field("SRC");
    dst = get_field("DST");
    spt = get_field("SPT");
    dpt = get_field("DPT");
    proto = get_field("PROTO");
    in_if = get_field("IN");
    out_if = get_field("OUT");
    pkt_len = get_field("LEN");
    ttl = get_field("TTL");
    src_mac = source_mac(get_field("MAC"), in_if, out_if, src, dst);
    event = event_type(proto, spt, dpt, dst);

    # Keep formatting concerns at the edge so parsing stays shared across all
    # output modes.
    if (format == "jsonl") {
        print_json();
    } else if (format == "csv") {
        print_csv();
    } else {
        print_text();
    }
}

# Clear per-event state. The fields array must be deleted because awk arrays
# keep keys from previous records unless explicitly reset.
function reset_event(    k) {
    delete fields;
    raw = ts = action = src = dst = spt = dpt = proto = in_if = out_if = "";
    pkt_len = ttl = src_mac = event = "";
}

function get_field(name) {
    return (name in fields) ? fields[name] : "";
}

function source_mac(mac, in_if, out_if, src_ip, dst_ip,    part) {
    if (mac == "") {
        # Local outbound packets often have IN= empty and OUT=<iface>. In that
        # case, use the host interface MAC gathered before parsing began.
        if (out_if != "" && in_if == "" && out_if in local_macs) {
            return local_macs[out_if];
        }

        # Loopback has no meaningful Ethernet MAC address.
        if (in_if == "lo" || src_ip == "127.0.0.1" || dst_ip == "127.0.0.1" || src_ip == "::1" || dst_ip == "::1") {
            return "local";
        }
        return "unknown";
    }

    # On bridged Ethernet traffic UFW often logs MAC as:
    # dst-mac:src-mac:ethertype. The source host MAC occupies fields 7-12.
    split(mac, part, ":");
    if (length(part[7]) && length(part[8]) && length(part[9]) && length(part[10]) && length(part[11]) && length(part[12])) {
        return part[7] ":" part[8] ":" part[9] ":" part[10] ":" part[11] ":" part[12];
    }

    return mac;
}

function event_type(proto, spt, dpt, dst_ip) {
    # Classify protocol families that are useful during IR without claiming
    # every no-port packet is mDNS.
    if (proto == "ICMP" || proto == "ICMPv6") {
        return proto;
    }
    if (proto == "UDP" && (spt == "5353" || dpt == "5353" || dst_ip == "224.0.0.251" || dst_ip == "ff02::fb")) {
        return "mDNS";
    }
    if (dpt != "") {
        return "port";
    }
    return "packet";
}

function print_text(    marker, arrow, port, direction, extras) {
    marker = (action == "BLOCK") ? "!BLOCK!" : tolower(action);
    arrow = (action == "BLOCK") ? "--X" : "-->";
    port = (dpt == "") ? dst : dst ":" dpt;
    direction = src " " arrow " " port;

    if (spt != "") {
        extras = " spt:" spt;
    } else {
        extras = "";
    }
    if (in_if != "") {
        extras = extras " in:" in_if;
    }
    if (out_if != "") {
        extras = extras " out:" out_if;
    }
    if (event != "port") {
        extras = extras " event:" event;
    }

    printf "[ %s ] [ %s ] [ src-mac: %s %s %s%s ]\n", ts, marker, src_mac, direction, proto, extras;
}

function print_csv() {
    print csv(ts), csv(action), csv(in_if), csv(out_if), csv(src_mac), csv(src), csv(dst), csv(spt), csv(dpt), csv(proto), csv(event), csv(pkt_len), csv(ttl), csv(raw);
}

function print_json() {
    printf "{";
    json_pair("timestamp", ts, 0);
    json_pair("action", action, 1);
    json_pair("interface_in", in_if, 1);
    json_pair("interface_out", out_if, 1);
    json_pair("src_mac", src_mac, 1);
    json_pair("src_ip", src, 1);
    json_pair("dst_ip", dst, 1);
    json_pair("src_port", spt, 1);
    json_pair("dst_port", dpt, 1);
    json_pair("protocol", proto, 1);
    json_pair("event", event, 1);
    json_pair("length", pkt_len, 1);
    json_pair("ttl", ttl, 1);
    json_pair("raw", raw, 1);
    printf "}\n";
}

function json_pair(key, value, comma) {
    if (comma) {
        printf ",";
    }
    printf "\"%s\":\"%s\"", json_escape(key), json_escape(value);
}

function json_escape(value,    out, i, char) {
    out = "";
    for (i = 1; i <= length(value); i++) {
        char = substr(value, i, 1);
        if (char == "\\") {
            out = out "\\\\";
        } else if (char == "\"") {
            out = out "\\\"";
        } else if (char == "\b") {
            out = out "\\b";
        } else if (char == "\f") {
            out = out "\\f";
        } else if (char == "\n") {
            out = out "\\n";
        } else if (char == "\r") {
            out = out "\\r";
        } else if (char == "\t") {
            out = out "\\t";
        } else {
            out = out char;
        }
    }
    return out;
}

function csv(value,    escaped) {
    escaped = value;
    gsub(/"/, "\"\"", escaped);
    return "\"" escaped "\"";
}
' "$input"
